name: Code Review with CodeGuru

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeguru-review:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Step 2: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # North Virginia

    # Step 3: Add CodeGuru Reviewer Action
    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      with:
        source_path: . # Directory to analyze, adjust if needed
        s3_bucket: codeguru-reviewer-satya-bucket  # Your S3 Bucket

    # Step 4: Upload review result
    - name: Upload review result
      if: ${{ github.event_name != 'push' }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
